# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/text.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/text.proto',
  package='pbuf',
  syntax='proto3',
  serialized_options=b'Z\017protos/toolkits',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11protos/text.proto\x12\x04pbuf\"\x1e\n\x0eKeywordRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1f\n\x0fKeywordResponse\x12\x0c\n\x04text\x18\x01 \x03(\t\"-\n\x0eSummaryRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x03\"\x1f\n\x0fSummaryResponse\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x19\n\tTFRequest\x12\x0c\n\x04text\x18\x01 \x03(\t\"-\n\nTFResponse\x12\x1f\n\x07records\x18\x01 \x03(\x0b\x32\x0e.pbuf.TFRecord\"\'\n\x08TFRecord\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x32\xbe\x01\n\x04Text\x12@\n\x0f\x45xtractKeywords\x12\x14.pbuf.KeywordRequest\x1a\x15.pbuf.KeywordResponse\"\x00\x12?\n\x0e\x45xtractSummary\x12\x14.pbuf.SummaryRequest\x1a\x15.pbuf.SummaryResponse\"\x00\x12\x33\n\x0c\x45xtractTfIdf\x12\x0f.pbuf.TFRequest\x1a\x10.pbuf.TFResponse\"\x00\x42\x11Z\x0fprotos/toolkitsb\x06proto3'
)




_KEYWORDREQUEST = _descriptor.Descriptor(
  name='KeywordRequest',
  full_name='pbuf.KeywordRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='pbuf.KeywordRequest.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=57,
)


_KEYWORDRESPONSE = _descriptor.Descriptor(
  name='KeywordResponse',
  full_name='pbuf.KeywordResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='pbuf.KeywordResponse.text', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=90,
)


_SUMMARYREQUEST = _descriptor.Descriptor(
  name='SummaryRequest',
  full_name='pbuf.SummaryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='pbuf.SummaryRequest.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='count', full_name='pbuf.SummaryRequest.count', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=137,
)


_SUMMARYRESPONSE = _descriptor.Descriptor(
  name='SummaryResponse',
  full_name='pbuf.SummaryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='pbuf.SummaryResponse.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=170,
)


_TFREQUEST = _descriptor.Descriptor(
  name='TFRequest',
  full_name='pbuf.TFRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='pbuf.TFRequest.text', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=172,
  serialized_end=197,
)


_TFRESPONSE = _descriptor.Descriptor(
  name='TFResponse',
  full_name='pbuf.TFResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='records', full_name='pbuf.TFResponse.records', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=199,
  serialized_end=244,
)


_TFRECORD = _descriptor.Descriptor(
  name='TFRecord',
  full_name='pbuf.TFRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='pbuf.TFRecord.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='score', full_name='pbuf.TFRecord.score', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=285,
)

_TFRESPONSE.fields_by_name['records'].message_type = _TFRECORD
DESCRIPTOR.message_types_by_name['KeywordRequest'] = _KEYWORDREQUEST
DESCRIPTOR.message_types_by_name['KeywordResponse'] = _KEYWORDRESPONSE
DESCRIPTOR.message_types_by_name['SummaryRequest'] = _SUMMARYREQUEST
DESCRIPTOR.message_types_by_name['SummaryResponse'] = _SUMMARYRESPONSE
DESCRIPTOR.message_types_by_name['TFRequest'] = _TFREQUEST
DESCRIPTOR.message_types_by_name['TFResponse'] = _TFRESPONSE
DESCRIPTOR.message_types_by_name['TFRecord'] = _TFRECORD
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

KeywordRequest = _reflection.GeneratedProtocolMessageType('KeywordRequest', (_message.Message,), {
  'DESCRIPTOR' : _KEYWORDREQUEST,
  '__module__' : 'protos.text_pb2'
  # @@protoc_insertion_point(class_scope:pbuf.KeywordRequest)
  })
_sym_db.RegisterMessage(KeywordRequest)

KeywordResponse = _reflection.GeneratedProtocolMessageType('KeywordResponse', (_message.Message,), {
  'DESCRIPTOR' : _KEYWORDRESPONSE,
  '__module__' : 'protos.text_pb2'
  # @@protoc_insertion_point(class_scope:pbuf.KeywordResponse)
  })
_sym_db.RegisterMessage(KeywordResponse)

SummaryRequest = _reflection.GeneratedProtocolMessageType('SummaryRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUMMARYREQUEST,
  '__module__' : 'protos.text_pb2'
  # @@protoc_insertion_point(class_scope:pbuf.SummaryRequest)
  })
_sym_db.RegisterMessage(SummaryRequest)

SummaryResponse = _reflection.GeneratedProtocolMessageType('SummaryResponse', (_message.Message,), {
  'DESCRIPTOR' : _SUMMARYRESPONSE,
  '__module__' : 'protos.text_pb2'
  # @@protoc_insertion_point(class_scope:pbuf.SummaryResponse)
  })
_sym_db.RegisterMessage(SummaryResponse)

TFRequest = _reflection.GeneratedProtocolMessageType('TFRequest', (_message.Message,), {
  'DESCRIPTOR' : _TFREQUEST,
  '__module__' : 'protos.text_pb2'
  # @@protoc_insertion_point(class_scope:pbuf.TFRequest)
  })
_sym_db.RegisterMessage(TFRequest)

TFResponse = _reflection.GeneratedProtocolMessageType('TFResponse', (_message.Message,), {
  'DESCRIPTOR' : _TFRESPONSE,
  '__module__' : 'protos.text_pb2'
  # @@protoc_insertion_point(class_scope:pbuf.TFResponse)
  })
_sym_db.RegisterMessage(TFResponse)

TFRecord = _reflection.GeneratedProtocolMessageType('TFRecord', (_message.Message,), {
  'DESCRIPTOR' : _TFRECORD,
  '__module__' : 'protos.text_pb2'
  # @@protoc_insertion_point(class_scope:pbuf.TFRecord)
  })
_sym_db.RegisterMessage(TFRecord)


DESCRIPTOR._options = None

_TEXT = _descriptor.ServiceDescriptor(
  name='Text',
  full_name='pbuf.Text',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=288,
  serialized_end=478,
  methods=[
  _descriptor.MethodDescriptor(
    name='ExtractKeywords',
    full_name='pbuf.Text.ExtractKeywords',
    index=0,
    containing_service=None,
    input_type=_KEYWORDREQUEST,
    output_type=_KEYWORDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ExtractSummary',
    full_name='pbuf.Text.ExtractSummary',
    index=1,
    containing_service=None,
    input_type=_SUMMARYREQUEST,
    output_type=_SUMMARYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ExtractTfIdf',
    full_name='pbuf.Text.ExtractTfIdf',
    index=2,
    containing_service=None,
    input_type=_TFREQUEST,
    output_type=_TFRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TEXT)

DESCRIPTOR.services_by_name['Text'] = _TEXT

# @@protoc_insertion_point(module_scope)
